//Fecha:  sábado 06 Setiembre 2025 
//Autor: Ana Roncal 

#ifndef LISTASIMPLEMENTEENLAZADA_ELEMENTOLISTA_H
#define LISTASIMPLEMENTEENLAZADA_ELEMENTOLISTA_H
struct ElementoLista {
    int cod;
};
#endif //LISTASIMPLEMENTEENLAZADA_ELEMENTOLISTA_H